### ISSUE TITLE
Demo app url links to non-existent site

### ISSUE THREAD

**Issue by akapocsi** [plotly/dash-svm#7]
https://dash-svm.plot.ly/ is listed in README.md and redirects to https://dash-gallery.plotly.host/dash-svm

https://dash-gallery.plotly.host/dash-svm throws a 404 error

There are several dead links here as well: https://dash.plot.ly/gallery

**Comment by xhlulu** [comment]
Hi @akapocsi, thanks for reporting the issue. The problem was on the hosting side. We re-deployed the app and it should work now. We are working on the other dead links now!
